---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    team: sre
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-demo
  namespace: demo
  labels:
    app: oom-demo
    team: sre
    language: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-demo
  template:
    metadata:
      labels:
        app: oom-demo
        team: sre
        language: java
    spec:
      containers:
        - name: oom-demo
          image: oom-demo:latest
          imagePullPolicy: Never   # use Minikube local image
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "96Mi"      # kernel OOMKills when this is breached
              cpu: "200m"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Always
  strategy:
    type: Recreate
