apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: synthetic
  labels:
    app: order-service
    team: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "9464"    # OTel Java agent Prometheus endpoint
        prometheus.io/path:   "/metrics"
        loki.grafana.com/log-format: "json"
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9464
              name: metrics
          env:
            - name: SERVICE_NAME
              value: "order-service"
            - name: SERVICE_VERSION
              value: "1.8.3"
            - name: ENVIRONMENT
              value: "production"
            - name: PORT
              value: "8080"
            # OTel Java agent config
            - name: OTEL_SERVICE_NAME
              value: "order-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production,service.version=1.8.3"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "prometheus"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_EXPORTER_PROMETHEUS_PORT
              value: "9464"
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "15000"
          resources:
            requests:
              memory: "96Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet: {path: /health, port: 8080}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet: {path: /health, port: 8080}
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: synthetic
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30800
    - name: metrics
      port: 9464
      targetPort: 9464
  type: NodePort
