/**
 * Renders an architecture diagram.
 *
 * Props:
 *   svgDef          — raw SVG string generated by the Python aws_diagram module (preferred)
 *   mermaidDef      — Mermaid diagram string (fallback when svgDef absent)
 *   architectureName — used for filename when downloading
 */
import { useEffect, useRef, useState } from "react";
import { ZoomIn, ZoomOut, Download, Maximize2 } from "lucide-react";

// ── Mermaid lazy-loader ───────────────────────────────────────────────────────

let _mermaidReady = false;
let _mermaid = null;

async function getMermaid() {
  if (_mermaidReady) return _mermaid;
  const m = await import("mermaid");
  _mermaid = m.default;
  _mermaid.initialize({
    startOnLoad: false,
    theme: "dark",
    themeVariables: {
      background: "#0a0a0c",
      primaryColor: "#1e3a5f",
      primaryTextColor: "#93c5fd",
      lineColor: "#475569",
      secondaryColor: "#14532d",
      tertiaryColor: "#3b0764",
      edgeLabelBackground: "#1e293b",
      clusterBkg: "#0f172a",
      clusterBorder: "#334155",
      fontFamily: "JetBrains Mono, ui-monospace, monospace",
      fontSize: "13px",
    },
    flowchart: { curve: "basis", padding: 20, htmlLabels: true },
    securityLevel: "loose",
  });
  _mermaidReady = true;
  return _mermaid;
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function ArchitectureDiagram({ svgDef, mermaidDef, architectureName }) {
  const containerRef = useRef(null);
  const [renderedSvg, setRenderedSvg] = useState("");
  const [error, setError] = useState("");
  const [zoom, setZoom] = useState(1);
  const [fullscreen, setFullscreen] = useState(false);

  // Prefer svgDef; fall back to mermaid rendering
  useEffect(() => {
    if (svgDef) {
      setRenderedSvg(svgDef);
      setError("");
      return;
    }
    if (!mermaidDef) return;

    let cancelled = false;
    async function render() {
      try {
        const m = await getMermaid();
        const id = `mermaid-${Date.now()}`;
        const { svg: out } = await m.render(id, mermaidDef);
        if (!cancelled) { setRenderedSvg(out); setError(""); }
      } catch (e) {
        if (!cancelled) { setError(e.message || "Diagram render failed"); }
      }
    }
    render();
    return () => { cancelled = true; };
  }, [svgDef, mermaidDef]);

  function download() {
    const content = svgDef || renderedSvg;
    const blob = new Blob([content], { type: "image/svg+xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${architectureName || "architecture"}.svg`;
    a.click();
    URL.revokeObjectURL(url);
  }

  if (!svgDef && !mermaidDef) return null;

  const panel = (
    <div className={`relative ${fullscreen ? "fixed inset-0 z-[100] bg-[#0a0a0c] flex flex-col" : ""}`}>
      {/* Toolbar */}
      <div className={`flex items-center justify-between px-4 py-2 border-b border-[var(--border-subtle)] bg-[var(--bg-surface)] ${fullscreen ? "" : "rounded-t-xl"}`}>
        <div className="flex items-center gap-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-red-500/60" />
          <div className="w-2.5 h-2.5 rounded-full bg-amber-500/60" />
          <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/60" />
          <span className="ml-3 text-[11px] font-mono text-[var(--text-muted)]">
            {architectureName || "architecture"}.svg
          </span>
          {svgDef && (
            <span className="ml-2 text-[9px] font-semibold px-1.5 py-0.5 rounded-full bg-[#FF9900]/10 text-[#FF9900] border border-[#FF9900]/20 uppercase tracking-wider">
              AWS
            </span>
          )}
        </div>
        <div className="flex items-center gap-1">
          <button onClick={() => setZoom(z => Math.max(0.3, z - 0.15))}
            className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-faint)] hover:text-[var(--text-secondary)] transition-colors" title="Zoom out">
            <ZoomOut size={13} />
          </button>
          <span className="text-[10px] text-[var(--text-faint)] w-10 text-center font-mono">{Math.round(zoom * 100)}%</span>
          <button onClick={() => setZoom(z => Math.min(3, z + 0.15))}
            className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-faint)] hover:text-[var(--text-secondary)] transition-colors" title="Zoom in">
            <ZoomIn size={13} />
          </button>
          <button onClick={download}
            className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-faint)] hover:text-[var(--text-secondary)] transition-colors" title="Download SVG">
            <Download size={13} />
          </button>
          <button onClick={() => setFullscreen(f => !f)}
            className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-faint)] hover:text-[var(--text-secondary)] transition-colors" title={fullscreen ? "Exit fullscreen" : "Fullscreen"}>
            <Maximize2 size={13} />
          </button>
        </div>
      </div>

      {/* Diagram canvas */}
      <div
        ref={containerRef}
        className={`overflow-auto bg-[#0d1525] ${fullscreen ? "flex-1" : "rounded-b-xl"}`}
        style={{ minHeight: fullscreen ? "auto" : "300px", maxHeight: fullscreen ? "none" : "540px" }}
      >
        {error ? (
          <div className="p-4 text-xs text-red-400 font-mono">{error}</div>
        ) : renderedSvg ? (
          <div
            className="p-4 flex items-start justify-center min-h-full"
            style={{
              transform: `scale(${zoom})`,
              transformOrigin: "top center",
              transition: "transform 0.15s ease",
            }}
            dangerouslySetInnerHTML={{ __html: renderedSvg }}
          />
        ) : (
          <div className="flex items-center justify-center h-40 text-[var(--text-faint)] text-sm">
            <span className="animate-pulse">Rendering diagram…</span>
          </div>
        )}
      </div>
    </div>
  );

  return (
    <div>
      <div className="rounded-xl border border-[var(--border-subtle)] overflow-hidden">
        {panel}
      </div>
      {fullscreen && (
        <div className="fixed inset-0 z-[99] bg-[#0a0a0c]" onClick={() => setFullscreen(false)}>
          <div className="absolute inset-4 rounded-2xl border border-[var(--border-default)] overflow-hidden" onClick={e => e.stopPropagation()}>
            {panel}
          </div>
        </div>
      )}
    </div>
  );
}
